---
title: "Publications"
---

<div style="margin-bottom:50px;">
</div>

### Journal articles
<details> 
    <summary class="pubstitle"> 
      **Nowack, D.**, & Leininger, J. (2022). Protecting democracy from abroad: democracy aid against attempts to circumvent presidential term limits. *Democratization*, 29 (1), 154-173. | [**Fulltext**](https://www.tandfonline.com/doi/full/10.1080/13510347.2021.1957840) | [**Data**](https://heidata.uni-heidelberg.de/dataset.xhtml?persistentId=doi:10.11588/data/EMUXDX) </summary>
    <br><p class="tab">The article addresses the question of whether international democracy aid helps to protect presidential term limits – a commonly accepted but increasingly challenged safeguard for democracy. According to our analysis, democracy aid is effective in countering attempts to circumvent term limits, thus, it contributed towards protecting democratic standards in African and Latin American countries between 1990 and 2014. Democracy aid helps to fend off term-limit circumventions, but it is not as effective in deterring presidents from trying to circumvent presidential term limits. Our analysis furthermore suggests that there is double the risk of an attempt to circumvent term limits in Latin American than in African states. Although our results confirm prior findings that “targeted aid” such as democracy aid makes a difference for maintaining democratic institutions, it challenges studies that argue democracy assistance has become “tame.” Our findings furthermore support previous indications that more refined theories on the effects of democracy aid in different phases of domestic processes are necessary, in particular in the face of global autocratization trends.</p>
</details>

<div style="margin-bottom:20px;">
</div>

<details> 
  <summary class="pubstitle"> 
    Leininger, J., & **Nowack, D.**. (2022). Protection against         autocratisation: how international democracy promotion helped preserve presidential term limits in Malawi and Senegal. *Third World Quarterly*, 43 (2), 309-331. | [**Fulltext**](https://www.tandfonline.com/doi/full/10.1080/01436597.2021.2000855)</summary>
  <br><p class="tab">This article analyses the conditions under which international democracy support contributes to protecting presidential term limits. As autocratisation has become an unwelcome global trend, researchers turned to the study of the toolboxes of would-be autocrats, including their attempts to circumvent term limits. Through a paired comparison of failed attempts in Malawi (2002) and Senegal (2012), we find that external democracy support can assist domestic actors and institutions in deflecting challenges to term limits. We offer a novel qualitative analysis that posits that international democracy support can only be effective if sustained by popular democratic attitudes and behaviours of actors in the recipient state. On the one hand, a mix of conditioning relations with the incumbent government while capacitating pro-democratic opposition is a successful strategy in aid-dependent political regimes with a minimum democratic quality. On the other, societal attitudes factor into decision-making at domestic and international levels. Our results suggest that popular pro-democratic attitudes encouraged international democracy support during critical junctures in the two countries, i.e. when incumbents attempted to circumvent term limitation. Donor investments had positive results when donors had directed resources towards building up civil society organisations long before any attempts at circumventing term limits were made</p>
</details>

<div style="margin-bottom:20px;">
</div>

<details> 
  <summary class="pubstitle"> 
    **Nowack, D.**. (2021). Process tracing the term limit struggle in Malawi: the role of international democracy promotion in Muluzi's bid for a third term, *Africa Spectrum*, 55 (3), 291-320. | [**Fulltext**](https://journals.sagepub.com/doi/10.1177/0002039720962119)</summary>
  <br><p class="tab">Attempts to circumvent presidential term limits in African countries show a puzzling variation of success or failure. This variation is due to both international and domestic factors. However, how these interact is not yet well understood. This article analyses how international donors and organisations intervened in the attempted term limit circumvention in Malawi from 1999 to 2003. It differentiates between different types of instruments used by donors in democracy promotion, and, by doing so, contributes to the question whether donors in term limit struggles can contribute to genuine democratic consolidation. It employs deductive process-tracing based on an analysis of primary media sources and interviews conducted during field research. The results show that erosion of party support as a proximate and a strong civil society response as a mediate factor were important in saving Malawi’s term limit. Aid conditionality and democracy promotion by donors and international organisations exerted influence on both factors.</p>
</details>


<div style="margin-bottom:50px;">
</div>


### Discussion and working papers
<details> 
  <summary class="pubstitle"> 
    Leininger, J., Burchi, F., Fiedler, C., Mross, K., **Nowack, D.**, von Schiller, A., Sommer, C., Strupat, C., & Ziaja, S. (2021). *Social cohesion: a new definition and a proposal for its measurement in Africa*. Discussion Paper 31/2021. Bonn: German Development Institute / Deutsches Institut für Entwicklungspolitik (DIE). | [**Fulltext**](https://www.idos-research.de/uploads/media/DP__31.2021.v1.1.pdf)</summary>
  <br><p class="tab">Social cohesion is key for sustainable development. While social cohesion has suffered in many societies from the consequences of the Covid-19 pandemic, high levels of social cohesion have helped to overcome critical situations during the pandemic in other societies. As a consequence, protecting and strengthening social cohesion has become an increasingly central goal for most countries and the international community. Despite the strong interest in the topic, the questions of how to define social cohesion and make it an observable phenomenon through proper measurement are still contested, in both academia and policy circles. To date, no consistent, temporally and geographically spread-out data on the different elements of social cohesion exists that would allow for a global analysis of social cohesion. This rather fragmented picture of analytical approaches calls for a more universal definition and measurement of social cohesion. This paper aims to provide a narrow and measurable definition of social cohesion that travels across regions and countries. Conceptually, it proposes a definition of social cohesion that incorporates the core elements of existing and widely used definitions of social cohesion across disciplines (trust, identity, cooperation for the common good). Our contribution is to offer a definition of social cohesion that is broad enough to cover the essentials holding societies together while at the same time keeping it lean enough to analyse the causes and consequences of social cohesion, for instance the relationship between social cohesion and inequalities or political institutions. Methodologically, we propose an application of our concept to the African context. It is not only a first step towards a more global and inter-regional measurement of social cohesion, but also the basis for further knowledge-creation, the identification of patterns of social cohesion and the analysis of its causes and consequences. From a policy-oriented perspective, a more unified definition of the core elements of social cohesion and its measurement can inform policies that aim at protecting and fostering social cohesion. In development cooperation, it will help not only to build indicators for designing programme objectives and for evaluation and monitoring, but also to advance evidence-based theories of change.</p>
</details>

<div style="margin-bottom:20px;">
</div>

<details> 
  <summary class="pubstitle"> 
    **Nowack, D.**, & Schoderer, S. (2020). *The role of values for social cohesion: theoretical explication and empirical exploration*. Discussion Paper 6/2020. Bonn: German Development Institute / Deutsches Institut für Entwicklungspolitik (DIE). | [**Fulltext**](https://www.idos-research.de/uploads/media/DP_6.2020.pdf)</summary>
  <br><p class="tab">Shared values are deemed necessary as a solid foundation for social cohesion by commentators and observers in many countries. However, when examining what kind of values this is based on, answers often come down to platitudes and national clichés. This discussion paper offers some clarification through both a theoretical explication and an empirical exploration concerning the general role of values for social cohesion.
Values are notions about desirable, trans-situational end-states and behaviours. They fall into two categories, individual and societal values. We provide a critical discussion of the most prominent conceptualisations and their operationalisation in the social sciences.
Values affect social cohesion in three possible pathways: First, when they are shared; second, when they promote behaviour per se conducive to social cohesion and third, through their effect on policy choice and institutional design. We review evidence provided by the research literature for each of these pathways.
We further explore the third pathway by deriving from the research literature the conjecture that a cultural value emphasis on egalitarianism makes a universalistic scope of welfare institutions more likely, which in turn increases social and political trust. We first examine this conjecture with a series of regression models, and then run a mediation analysis. The results show that (1.) egalitarian values are moderately strongly and positively linked to universalistic welfare institutions, but that (2.) welfare institutions mediate the association of egalitarian values with social trust only to a small extent and that (3.) more universalistic welfare institutions counteract a negative association between egalitarian values and institutional trust.</p>
</details>

<div style="margin-bottom:20px;">
</div>

<details> 
  <summary class="pubstitle"> 
    **Nowack, D.** (2018). *Cultural values, attitudes, and democracy promotion in Malawi: how values mediate the effectiveness of donor support for the reform of presidential term limits and family law*. Discussion Paper 27/2018. Bonn: German Development Institute / Deutsches Institut für Entwicklungspolitik (DIE). | [**Fulltext**](https://www.idos-research.de/uploads/media/DP_27.2018.pdf)</summary>
  <br><p class="tab">This Discussion Paper is part of the larger research project “What is Democracy’s Value? The Influence of Values on the Effectiveness of Democracy Promotion”, which aims at understanding how societal values and attitudes influence the effectiveness of international democracy promotion in African countries. The project looks at how social values and political attitudes mediate the promotion of democracy in two specific realms: attempts by heads of state to circumvent presidential term limits; and reforms to legislation in the realm of family law and LGBTI (Lesbian, Gay, Bisexual, Transsexual, Intersex) rights. This Discussion Paper focuses on two cases situated in Malawi: the attempt of former president Bakili Muluzi to alter presidential term limits in Malawi in 2002; and the reform of Malawi’s family and marriage law in 2015. In both cases, donors engaged in democracy promotion in different ways and to different degrees. In the former case, donor countries and organisations warned the Muluzi government to heed the democratic process and thereby seconded popular attitudes. In the latter, donor countries and organisations played an important role in coordinating and mobilising domestic actors towards the reform of Malawi’s family and marriage law.</p>
</details>

<div style="margin-bottom:50px;">
</div>


### Doctoral thesis
<details> 
  <summary class="pubstitle"> 
    **Nowack, D.** (2023). *Democracy promotion and presidential term limits*. PhD thesis, 9 May 2023. Heidelberg: Institute of Political Science, Ruprecht-Karls Universität Heidelberg. | [**Fulltext**](https://archiv.ub.uni-heidelberg.de/volltextserver/33207/7/Thesis_Nowack2022.pdf)</summary>
  <br><p class="tab">The end of the Cold War saw an unprecedented diffusion of democracy. This diffusion went hand in hand with the emergence of international democracy promotion. Through democracy promotion, democratic states attempt to support and protect democratic institutions around the world by means of bilateral and multilateral international cooperation as well as development cooperation. Yet, the 'wave of democratization' has ebbed away since the Cold War. Rather than an anabated spread of democracy, many countries that seemed on a transition-path to democracy are now stuck in a political state between autocracy and democracy, where democratic institutions formally exist but are compromised by authoritarian practices. Moreover, populist movements, illiberalism, and non-democratic institutional changes seem to challenge democracy as a political system even in countries where it was long since regarded as historically and socially consolidated. This as well as the increasing confidence of authoritarian regimes threaten to jeopardize the strides that worldwide democratization has made in the past three decades.
Against this setting, the present thesis investigates the effectiveness of international democracy promotion in supporting and guarding the democratic institutionalization of political power. The research presented here zooms in on presidential term limits, a political institution meant to prevent the personalization of political power and ensure rotation in presidential office. While it was characteristic for countries, particularly in sub-Saharan Africa, that began transitioning to democracy at the end of the Cold War to introduce presidential term limits in their newly designed constitutions, many of these provisions have since been challenged by incumbent presidents. Research shows that the evasion of term limits is associated with a worsening of the general state of democracy in a country. Evasion of presidential term limits is thus seen as an important manifestation for the weak institutionalization and further de-institutionalization of democracy. Although presidential term limits and in particular their circumvention have hence become a subject matter of interest to political scientists, many scholars do not focus in this regard explicitly on the role of international democracy support. I address this gap by studying the influence that international democracy promotion has on the evasion and introduction of presidential term limits.
The first chapter provides a conceptual and theoretical introduction to presidential term limits and their relation to the weak institutionalization of democracy. Democracy promotion and the different forms it may take is also introduced before a brief outlook on the thesis is presented. In chapter two my co-author and I present a broad perspective on how democracy aid, which is the implementation of democracy promotion as foreign aid in development cooperation, is associated with the risk that presidents attempt to evade term limits as well as that they actually succeed in doing so.
In chapter three, my co-author and I undertake a qualitative paired comparison of two cases where incumbent presidents attempted to circumvent a term limit but failed at different stages during the process. We compare the role that different means, or 'instruments' of democracy promotion played in both cases and how their effectiveness was predicated on favourable domestic conditions, particularly popular pro-democratic attitudes.
In chapter four, I provide an 'in-depth' description of one of the two cases. The chapter employs a qualitative methodology designed to trace closely the influence of different factors for an outcome. I make use of this by systematically assessing how different democracy promotion instruments acted alone and in conjunction with domestic factors on the case's outcome.
Finally, chapter five shifts the focus from the evasion of term limits to the introduction of term limits. Interested in the 'on-the-ground' practice of democracy promotion during ad hoc emerging reform episodes, I study the interactions between on the one hand domestic civil society and political opposition parties and on the other hand external embassies and international organizations.
The research results show that international democracy promotion often has a limited, conditional influence on preventing the de-institutionalization of democracy. While it is evident according to a presented statistical analysis that democracy promotion through foreign aid is associated with lower risks of term limit evasions, this relation is substantial in effect size only for medium to high \emph{per capita}-amounts of democracy aid. Furthermore, results of the qualitative case studies show that democracy promotion operates through largely two mechanisms, a 'hard power' mechanism functioning according to a logic of consequentiality, conditionality, and leverage; and a 'soft power' mechanism functioning according to a logic of appropriateness and linkage. However, both work best in tandem, and are predicated on domestic conditions, particularly on favourable popular (pro-)democratic attitudes and a civil society that is free to mobilize. Finally, the research presented here also emphasizes the quandaries to which democracy promoters themselves are subject, especially when they need to respond ad hoc to a push for political liberalization in an hitherto (semi-)authoritarian country context.
The thesis contributes to two interescting research fields, one on the evasion of presidential term limits, and the other on the role that international democracy support can play in preserving and promoting democratic institutions. Its results suggest policy implications particularly for the practice and implementation of democracy promotion. Foremost among these are that the level of spending of democracy aid in development cooperation as well as its temporal continuation can have substantial effects on guarding democratic institutions (chapter two); that 'hard power' and 'soft power' approaches of democracy promotion need to be used wisely in complementarity to one another (chapter three and four); that foreign states and international organizations need to react decisively against the curbing of the civic space, and also need to defend institutions integral to 'democracy as democracy' against transgressions and violations (chapters three to five); and finally, that democracy supporters, particularly foreign governments as democracy supporters, need to critically reflect on self-imposed internal restraints besides encountered external constraints in the practice of international democracy promotion.</p>
</details>

<div style="margin-bottom:50px;">
</div>